version: '3.3'

services:
  mongodb:
    image: 'bitnami/mongodb:4.2.8'
    environment:
      - MONGODB_DATABASE=test
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_PORT_NUMBER=27017
    ports:
      - "27017:27017"
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local